openapi: 3.2.0
info:
  title: SS&C Eze EMS X User Services API
  version: v2026.5.0
security:
- Bearer: []
tags:
- name: UserServices
paths:
  /api/v1/user/user-permissions:
    get:
      tags:
      - UserServices
      parameters:
      - name: UserToken
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserPermissionsResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Google.Rpc.Status'
      summary: Get api user user permissions
      x-summary-source: derived
      operationId: getApiV1UserUserPermissions
      x-operation-id-source: derived
components:
  schemas:
    Google.Protobuf.WellKnownTypes.Value:
      type: object
      properties:
        nullValue:
          $ref: '#/components/schemas/Google.Protobuf.WellKnownTypes.NullValue'
        hasNullValue:
          type: boolean
          readOnly: true
        numberValue:
          type: number
          format: double
        hasNumberValue:
          type: boolean
          readOnly: true
        stringValue:
          type:
          - string
          - 'null'
        hasStringValue:
          type: boolean
          readOnly: true
        boolValue:
          type: boolean
        hasBoolValue:
          type: boolean
          readOnly: true
        structValue:
          $ref: '#/components/schemas/Google.Protobuf.WellKnownTypes.Struct'
        listValue:
          $ref: '#/components/schemas/Google.Protobuf.WellKnownTypes.ListValue'
        kindCase:
          $ref: '#/components/schemas/Google.Protobuf.WellKnownTypes.ValueKindOneofCase'
      additionalProperties: false
    Google.Protobuf.WellKnownTypes.ListValue:
      type: object
      properties:
        values:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Google.Protobuf.WellKnownTypes.Value'
          readOnly: true
      additionalProperties: false
    Google.Protobuf.WellKnownTypes.Struct:
      type: object
      properties:
        fields:
          type:
          - object
          - 'null'
          additionalProperties:
            $ref: '#/components/schemas/Google.Protobuf.WellKnownTypes.Value'
          readOnly: true
      additionalProperties: false
    UserPermissionRecord:
      type: object
      properties:
        Bank:
          type: string
        Branch:
          type: string
        Customer:
          type: string
        Deposit:
          type: string
        AcctType:
          type: integer
          format: int32
        MarginSource:
          type: integer
          format: int32
        MarginRulesetId:
          type: integer
          format: int32
        MarginRulesetName:
          type: string
        AcctDesc:
          type: string
      additionalProperties: false
    Google.Protobuf.WellKnownTypes.ValueKindOneofCase:
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      type: integer
      format: int32
    ServerAcknowledgement:
      type: object
      properties:
        ServerResponse:
          type: string
        OptionalFields:
          type: object
          additionalProperties:
            type:
            - string
            - 'null'
        Message:
          type: string
        ResponseCode:
          $ref: '#/components/schemas/ServerAcknowledgementTypesResponseCodesEnum'
      additionalProperties: false
    GetUserPermissionsResponse:
      type: object
      properties:
        Permissions:
          type: array
          items:
            $ref: '#/components/schemas/UserPermissionRecord'
        Acknowledgement:
          $ref: '#/components/schemas/ServerAcknowledgement'
      additionalProperties: false
    ServerAcknowledgementTypesResponseCodesEnum:
      enum:
      - SUCCESS
      - WARNING
      - FAILED
      - ERROR
      - TIMED_OUT
      - SESSION_NOT_FOUND
      type: string
    Google.Rpc.Status:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/Google.Protobuf.WellKnownTypes.Any'
      additionalProperties: false
    Google.Protobuf.WellKnownTypes.NullValue:
      enum:
      - 0
      type: integer
      format: int32
    Google.Protobuf.WellKnownTypes.Any:
      required:
      - '@type'
      type: object
      properties:
        '@type':
          type: string
      additionalProperties:
        $ref: '#/components/schemas/Google.Protobuf.WellKnownTypes.Value'
  securitySchemes:
    Bearer:
      type: http
      description: 'Please enter a valid token : '
      scheme: Bearer
      bearerFormat: JWT
